tomes:
  dirt:
    cost: 10
    rewards:
      items:
      weights:
    slayer:
      entities:
        "0": "SKELETON"
        "1": "ZOMBIE"
        "2": "CREEPER"
        "3": "SPIDER"
        "4": "ENDERMAN"
      minNumbers:
        "0": 1
        "1": 1
        "2": 1
        "3": 1
        "4": 1
      maxNumbers:
        "0": 10
        "1": 10
        "2": 10
        "3": 10
        "4": 5
    mine:
      materials:
        "0": "COAL_ORE"
        "1": "IRON_ORE"
        "2": "GOLD_ORE"
        "3": "DIAMOND_ORE"
        "4": "EMERALD_ORE"
      minNumbers:
        "0": 1
        "1": 1
        "2": 1
        "3": 1
        "4": 1
      maxNumbers:
        "0": 200
        "1": 200
        "2": 100
        "3": 50
        "4": 20
  wood:
    cost: 20
    rewards:
      items:
      weights:
    slayer:
      entities:
        "0": "SKELETON"
        "1": "ZOMBIE"
        "2": "CREEPER"
        "3": "SPIDER"
        "4": "ENDERMAN"
      minNumbers:
        "0": 1
        "1": 1
        "2": 1
        "3": 1
        "4": 1
      maxNumbers:
        "0": 10
        "1": 10
        "2": 10
        "3": 10
        "4": 5
    mine:
      materials:
        "0": "COAL_ORE"
        "1": "IRON_ORE"
        "2": "GOLD_ORE"
        "3": "DIAMOND_ORE"
        "4": "EMERALD_ORE"
      minNumbers:
        "0": 1
        "1": 1
        "2": 1
        "3": 1
        "4": 1
      maxNumbers:
        "0": 200
        "1": 200
        "2": 100
        "3": 50
        "4": 20
  stone:
    cost: 30
    rewards:
      items:
      weights:
    slayer:
      entities:
        "0": "SKELETON"
        "1": "ZOMBIE"
        "2": "CREEPER"
        "3": "SPIDER"
        "4": "ENDERMAN"
      minNumbers:
        "0": 1
        "1": 1
        "2": 1
        "3": 1
        "4": 1
      maxNumbers:
        "0": 10
        "1": 10
        "2": 10
        "3": 10
        "4": 5
    mine:
      materials:
        "0": "COAL_ORE"
        "1": "IRON_ORE"
        "2": "GOLD_ORE"
        "3": "DIAMOND_ORE"
        "4": "EMERALD_ORE"
      minNumbers:
        "0": 1
        "1": 1
        "2": 1
        "3": 1
        "4": 1
      maxNumbers:
        "0": 200
        "1": 200
        "2": 100
        "3": 50
        "4": 20



