tomes:
  dirt:
    rewards:
      items:
      weights:
    slayer:
      entities:
        "0": "SKELETON"
        "1": "ZOMBIE"
        "2": "CREEPER"
        "3": "SPIDER"
        "4": "ENDERMAN"
      minNumbers:
        "0": 1
        "1": 1
        "2": 1
        "3": 1
        "4": 1
      maxNumbers:
        "0": 10
        "1": 10
        "2": 10
        "3": 10
        "4": 5
  wood:
    rewards:
      items:
      weights:
    slayer:
      entities:
        "0": "SKELETON"
        "1": "ZOMBIE"
        "2": "CREEPER"
        "3": "SPIDER"
        "4": "ENDERMAN"
      minNumbers:
        "0": 1
        "1": 1
        "2": 1
        "3": 1
        "4": 1
      maxNumbers:
        "0": 10
        "1": 10
        "2": 10
        "3": 10
        "4": 5
  stone:
    rewards:
      items:
      weights:
    slayer:
      entities:
        "0": "SKELETON"
        "1": "ZOMBIE"
        "2": "CREEPER"
        "3": "SPIDER"
        "4": "ENDERMAN"
      minNumbers:
        "0": 1
        "1": 1
        "2": 1
        "3": 1
        "4": 1
      maxNumbers:
        "0": 10
        "1": 10
        "2": 10
        "3": 10
        "4": 5



